### ISSUE TITLE
 Error Could not find org.jetbrains.kotlin:kotlin-stdlib1.4.20:1.4.20 saat mau gradle sync

### ISSUE THREAD

**Issue by arifikhsan** [dicodingacademy/a129-jetpack-labs#104]
**pesan error**
Could not find org.jetbrains.kotlin:kotlin-stdlib1.4.20:1.4.20

**masalah**
ada typo di file gradle (app). kurang tanda titik dua (**:**)

https://github.com/dicodingacademy/a129-jetpack-labs/blob/a80df12d00978dc2495404e35017486ba9b74f65/Project%20Academy/08.%20IdlingResource/kotlin/app/build.gradle#L40

jadinya:
```gradle
implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
```

**Comment by arifaizin** [comment]
Thanks for your feedback :)
